Directions=function(){this.display=new google.maps.DirectionsRenderer({draggable:!0});this.directionsService=new google.maps.DirectionsService;this.map=!1;this.markerA=new google.maps.Marker({draggable:!0});this.markerB=new google.maps.Marker({draggable:!0});this.markerA.setIcon("https://maps.gstatic.com/mapfiles/markers/marker_greenA.png");this.markerB.setIcon("https://maps.gstatic.com/mapfiles/markers/marker_greenB.png");this.poly=this.dragged=!1};var dirs=!1;
function do_stuff(){function d(a,b){var g="http://twitter.com/intent/tweet?text="+escape("Just posted a ")+b+"km ride share with @road_lk. Check it out! &url="+escape(a)+"&via=road_lk";$("#sm-buttons .twitter").attr("href",g);g="http://www.facebook.com/sharer/sharer.php?u="+escape(a);$("#sm-buttons .facebook").attr("href",g);g="https://plusone.google.com/_/+1/confirm?hl=en&url="+escape(a);$("#sm-buttons .googleplus").attr("href",g);var c="Found the perfect ride from stat to end using road.lk directions service. "+
escape(a);escape(c);$("#sm-buttons .email").attr("href",g)}function e(a){$.get("/carpool/route/"+a+"/",function(a){"empty"==a.message?(map.setCenter(google.maps.LatLng(7.132944,79.847778)),map.setZoom(9)):(thePoints=google.maps.geometry.encoding.decodePath(a.points),dirs.poly&&(dirs.poly.setVisible(!1),dirs.poly.setMap(null)),dirs.poly=new google.maps.Polyline({path:thePoints,levels:decodeLevels(a.levels),strokeColor:"#FF0000",strokeOpacity:.5,strokeWeight:5,geodesic:!0,map:dirs.map,visible:!0}),dirs.poly.setVisible(!0))})}
function l(){try{var a=/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})/.exec($("#start_time").val().trim());if(6==a.length){var b=new Date;b.setYear(a[1]);b.setMonth(a[2]-1);b.setDate(a[3]);b.setHours(a[4]);b.setMinutes(a[5]);if(b){if(b.valueOf()>=Date.now())return b.valueOf();if(p)$.bootstrapGrowl("Sorry can't match when the start time is in the past.");else return Date.now()}else return!1}}catch(g){return $.bootstrapGrowl("Please enter the time at which you wish to start your journey"),!1}}function f(a){$(".has-error").removeClass("has-error");
a=!0;$("#ride_ask").is(":checked")?a=!1:$("#ride_offer").is(":checked")?""==$("#rate").val()?$("#rate").parent().addClass("has-error"):45<$("#rate").val()?($("#rate").parent().addClass("has-error"),$.bootstrapGrowl("Please choose a value less than Rs 45 per kilometer")):a=!1:(a=!0,$("#ride_ask").parent().parent().addClass("has-error"));var b;"undefined"==typeof dirs.display.directions?(""==k.val().trim()&&k.parent().addClass("has-error"),""==h.val().trim()&&h.parent().addClass("has-error"),$.bootstrapGrowl("Please tell us where you will be starting from and your destination."),
b=!1):b=!0;if(!b||!l()||a)return!1;a=l();b=[];var g,c=dirs.display.directions.routes[0],d=c.legs[0];if(!a)return!1;if(!n&&!p)return $.bootstrapGrowl("You have already created this rideshare (please change some of the settings and try again)"),!1;x=y=p=n=!1;var e,m;e={lat:d.start_location.lat(),lng:d.start_location.lng()};m={lat:d.end_location.lat(),lng:d.end_location.lng()};g=d.via_waypoints;for(var f=0;f<g.length;f++)b[f]={lat:g[f].lat(),lng:g[f].lng()};$(".fa-spinner").addClass("fa-spin").show();
$.post("/carpool/new/",{start:d.start_address,end:d.end_address,poly:c.overview_polyline,way_points:JSON.stringify(b),share_type:$("#ride_ask").is(":checked")?0:1,start_pos:JSON.stringify(e),end_pos:JSON.stringify(m),start_time:a,repeat:$("#id_repeat").val(),rate:$("#rate").val()},function(a){if("Ok"==a.status){var b=a.id.split("_");$(".match-candidates").attr("attr-this-trip",b[1]);B(a)}else try{if("object"==typeof a.message)for(b in a.message){var c=$("#"+b);c.length&&c.parent().addClass("has-error")}else create_alert({txt:a.message})}catch(d){create_alert({txt:"Sorry but something went wrong ....."})}}).always(function(){$(".fa-spinner").removeClass("fa-spin").hide()});
return!0}function v(a,b,c){a.setMap(c);try{a.setPosition(b.geometry.location)}catch(d){a.setPosition(b)}}function z(){var a=w.getPlace();a&&a.geometry?(v(dirs.markerA,a,dirs.map),(a=q.getPlace())&&a.geometry?(v(dirs.markerB,a,dirs.map),calcRoute()):dirs.markerB&&dirs.markerB.getPosition()?calcRoute():dirs.map.setCenter(dirs.markerA.getPosition())):dirs.markerA&&dirs.markerA.getPosition()&&(a=q.getPlace())&&a.geometry&&(v(dirs.markerB,a,dirs.map),calcRoute())}function B(a){$.get(a.link,function(a){$(".match-candidates").html(a.content);
$("#panel2 .panel-heading").slideDown();$("#panel2").slideDown();$("#panel1 .collapse").collapse("hide");$("#panel1 .panel-heading").slideDown();$(".timestamp").length?$(".timestamp").each(function(){show_timing($(this),!1,$(this).hasClass("compact"));$(this).removeClass("hide")}):d("https://road.lk/carpool/"+$("#panel2 table").attr("attr-this-trip")+"/",a.distance)})}$(".nav > li:eq(3)").addClass("active");dirs=new Directions;$("#over_map");var n=!1,p=!1,k=$("#start"),h=$("#end"),A=new google.maps.Geocoder,
x=!1,y=!1,c={zoom:14,mapTypeId:google.maps.MapTypeId.ROADMAP,center:new google.maps.LatLng(6.907779,79.87045899999998),zoomControlOptions:{style:google.maps.ZoomControlStyle.DEFAULT,position:google.maps.ControlPosition.RIGHT_CENTER},panControlOptions:{position:google.maps.ControlPosition.TOP_RIGHT}};h.data("lat")&&h.data("lng")?c.center=new google.maps.LatLng($("#end").data("lat"),$("#end").data("lng")):k.data("lat")&&k.data("lng")&&(c.center=new google.maps.LatLng($("#start").data("lat"),$("#start").data("lng")));
$("#map_canvas").parent().css("padding","5px 0px");dirs.map=new google.maps.Map(document.getElementById("map_canvas"),c);google.maps.event.addListener(dirs.markerA,"dragend",function(){dirs.dragged=!0;A.geocode({location:dirs.markerA.getPosition()},function(a,b){a&&a.length&&k.val(a[0].formatted_address)})});google.maps.event.addListener(dirs.markerB,"dragend",function(){dirs.dragged=!0;A.geocode({location:dirs.markerB.getPosition()},function(a,b){a&&a.length&&h.val(a[0].formatted_address)})});google.maps.event.addListener(dirs.map,
"dragend",function(){dirs.dragged=!0});dirs.display.setMap(dirs.map);var r={componentRestrictions:{country:"lk"}},m=document.getElementById("start");if("undefined"!=typeof m&&m){var w=new google.maps.places.Autocomplete(m,r),m=document.getElementById("end"),q=new google.maps.places.Autocomplete(m,r);w.bindTo("bounds",dirs.map);q.bindTo("bounds",dirs.map);google.maps.event.addListener(w,"place_changed",function(){k.data("edited",!0);z()});google.maps.event.addListener(q,"place_changed",function(){h.data("edited",
!0);z()})}dirs.display.setPanel(document.getElementById("directions_panel"));$("form").on("submit",function(a){a.preventDefault()}).on("click",".route",function(a){a.preventDefault();calcRoute()}).on("click","#ride_ask",function(a){x||(n=!0);$("#rate").parent().slideUp()}).on("click","#ride_offer",function(a){y||(n=!0);$("#rate").parent().slideDown()}).on("click",".step1",function(a){f()});$(".route").removeClass("hide");$("#panel2").on("click","#sm-buttons>a",function(a){dirs.shareButton=$(this);
share_route(a)});$(".panel").css("border","0px");$("#link").length&&""!=$("#link").text().trim()?($.get("/navigation/"+$("#link").text().trim()+"/?js=1",function(a){var b=JSON.parse(a);a=JSON.parse(b.way_points);var c=[],e,f;d("https://road.lk/carpool/"+$("#panel2 table").attr("attr-this-trip")+"/",b.distance);k.val(b.start);h.val(b.end);for(b=0;b<a.coordinates.length;b++)0==b?e=new google.maps.LatLng(a.coordinates[b][1],a.coordinates[b][0]):b==a.coordinates.length-1?f=new google.maps.LatLng(a.coordinates[b][1],
a.coordinates[b][0]):c.push({stopover:!1,location:new google.maps.LatLng(a.coordinates[b][1],a.coordinates[b][0])});_calcRoute(e,f,c);p=n=!0}),$("#link2").length&&e($("#link2").text().trim())):(google.maps.event.addListener(dirs.display,"directions_changed",function(){var a=dirs.display.directions.routes[0].legs[0];n=!0;k.data("edited")||k.val(a.start_address);h.data("edited")||h.val(a.end_address);k.data("edited",!1);h.data("edited",!1);$(".match-candidates").html("");dirs.poly&&(dirs.poly.setVisibile(!1),
dirs.poly.setMap(null))}),h.data("lat")&&h.data("lng")&&(dirs.markerB.setPosition(c.center),dirs.markerB.setMap(dirs.map)));$(".match-candidates").on("click",".match",function(){$("table .success").removeClass("success");$(this).addClass("success");var a=$(this).attr("id");e(a)});$(".match-candidates").on("click",".btn",function(a){a.preventDefault();var b=$(this).parents(".match");$(this).hasClass("btn-danger")?$.post("/carpool/match/",{potential:b.attr("id"),action:"cancel"},function(a){"Ok"==a.status&&
b.slideUp()}):$(this).hasClass("details")?window.location.href="/carpool/match/"+b.attr("id")+"/":$.post("/carpool/match/",{potential:b.attr("id")},function(a){"Ok"==a.status&&window.location.assign(a.link)})});if($("#start_time").length){c=Date.now()+18E5;$("#start_time").data("initial")&&1E3*$("#start_time").data("initial")>c&&(c=1E3*$("#start_time").data("initial"));var c=new Date(c),r=10>c.getHours()?"0"+c.getHours():c.getHours(),m=10>c.getMinutes()?"0"+c.getMinutes():c.getMinutes(),t=c.getMonth()+
1;10>t&&(t="0"+t);var u=c.getDate();10>u&&(u="0"+u);$("#start_time").val(c.getFullYear()+"-"+t+"-"+u+" "+r+":"+m+":00");$("#start_time").datetimepicker({lang:"en",minDate:c,format:"Y-m-d H:i",step:15});$("#start_time").on("change",function(){p=!0})}k.attr("placeholder")?$("#over_map").removeClass("hide"):setTimeout(function(){$("#over_map").removeClass("hide")},1E3)}function decodeLevels(d){for(var e=[],l=0;l<d.length;++l){var f=d.charCodeAt(l)-63;e.push(f)}return e}
function share_route(d){var e="",e=dirs.shareButton.hasClass("facebook")?"width=626,height=436":"width=500,height=500";0==$("#mobile_view").length&&(window.open(dirs.shareButton.attr("href"),"Share directions",e),d.preventDefault())}function calcRoute(){var d=dirs.markerA.getPosition(),e=dirs.markerB.getPosition();document.getElementById("waypoints");_calcRoute(d,e,[])}
function _calcRoute(d,e,l){dirs.directionsService.route({origin:d,destination:e,waypoints:l,optimizeWaypoints:!0,provideRouteAlternatives:!0,travelMode:google.maps.DirectionsTravelMode.DRIVING,unitSystem:google.maps.UnitSystem.METRIC,durationInTraffic:!1},function(f,l){l==google.maps.DirectionsStatus.OK&&($(".help").length&&""==$(".help").html().trim()&&($(".help").html($("#directions_panel").html()),$("#directions_panel").html("")),dirs.display.setDirections(f),dirs.markerB.setPosition(e),dirs.markerA.setPosition(d),
dirs.markerB.setMap(null),dirs.markerA.setMap(null),dirs.dragged=!1,$("#link").length&&""!=$("#link").text().trim()||($("#panel3").slideDown("slow"),$("#panel3 .collapse").collapse("show"),$("#panel3 .panel-heading").slideDown("slow")))})}jQuery(document).ready(function(){function d(d){$(d.target).prev(".panel-heading").find("i.indicator").toggleClass("fa-angle-double-right fa-angle-double-up")}$("#control_panel").on("hidden.bs.collapse",d);$("#control_panel").on("shown.bs.collapse",d)});
